version: '3'
services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.giatotnhat.io.vn
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.giatotnhat.io.vn/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=172.17.0.1
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=@Admin123
      - N8N_PAYLOAD_SIZE_MAX=500MB
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=kimlongsoctrang22@gmail.com
      - N8N_SMTP_PASS=igaomjaavypozzwk
      - N8N_SMTP_SENDER=kimlongsoctrang22@gmail.com
      - N8N_SMTP_SSL=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
