version: '3'
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=giatotnhat.io.vn
      - N8N_PROTOCOL=http  # Đổi thành 'https' nếu dùng SSL
      - WEBHOOK_URL=http://giatotnhat.io.vn/  # Cấu hình webhook (đổi thành https nếu có SSL)
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
