version: '3'
services:
  # postgres:
  #   image: postgres:15
  #   container_name: postgres_n8n
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: n8n
  #     POSTGRES_PASSWORD: n8npassword
  #     POSTGRES_DB: n8n
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.giatotnhat.io.vn
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://n8n.giatotnhat.io.vn/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=103.82.195.159
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=admin
      - DB_POSTGRESDB_PASSWORD=Admin123
      - N8N_PAYLOAD_SIZE_MAX=500MB
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=kimlongsoctrang22@gmail.com
      - N8N_SMTP_PASS=igaomjaavypozzwk
      - N8N_SMTP_SENDER=kimlongsoctrang22@gmail.com
      - N8N_SMTP_SSL=false
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
  postgres_data:
