version: '4.0'
services:
  db_mysql_server:
    container_name: 'db_mysql_server'
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: Admin123
      MARIADB_DATABASE: test_database
      MARIADB_USER: admin
      MARIADB_PASSWORD: Admin123
    ports:
      - "3306:3306"
